
var g_resources = [
    //image

    //plist

    //fnt

    //tmx

    //bgm

    //effect
];

var res = {
    textureControl_png : 'res/exported/controlBar.png',
    textureTablet_png : 'res/exported/tablet.png',
    textureAssets01_png : 'res/exported/assets01.png',
    textureAssets02_png : 'res/exported/assets02.png',
    textureLine01_png : 'res/exported/line01.png',
    textureLine02_png : 'res/exported/line02.png',
    textureLine03_png : 'res/exported/line03.png',

    textureControl_plist : 'res/exported/controlBar.plist',
    textureTablet_plist : 'res/exported/tablet.plist',
    textureAssets01_plist : 'res/exported/assets01.plist',
    textureAssets02_plist : 'res/exported/assets02.plist',
    textureLine01_plist : 'res/exported/line01.plist',
    textureLine02_plist : 'res/exported/line02.plist',
    textureLine03_plist : 'res/exported/line03.plist',

    textureTile_png : 'res/exported/winLines/tile.png',
    textureTile_xml : 'res/exported/winLines/tile.xml',
    texturewinline001_xml : 'res/exported/winLines/winline-001.xml',
    texturewinline002_xml : 'res/exported/winLines/winline-002.xml',
    texturewinline003_xml : 'res/exported/winLines/winline-003.xml',
    texturewinline004_xml : 'res/exported/winLines/winline-004.xml',
    texturewinline005_xml : 'res/exported/winLines/winline-005.xml',
    texturewinline006_xml : 'res/exported/winLines/winline-006.xml',
    texturewinline007_xml : 'res/exported/winLines/winline-007.xml',
    texturewinline008_xml : 'res/exported/winLines/winline-008.xml',
    texturewinline009_xml : 'res/exported/winLines/winline-009.xml',
    texturewinline010_xml : 'res/exported/winLines/winline-010.xml',
    texturewinline011_xml : 'res/exported/winLines/winline-011.xml',
    texturewinline012_xml : 'res/exported/winLines/winline-012.xml',
    texturewinline013_xml : 'res/exported/winLines/winline-013.xml',
    texturewinline014_xml : 'res/exported/winLines/winline-014.xml',
    texturewinline015_xml : 'res/exported/winLines/winline-015.xml',
    texturewinline016_xml : 'res/exported/winLines/winline-016.xml',
    texturewinline017_xml : 'res/exported/winLines/winline-017.xml',
    texturewinline018_xml : 'res/exported/winLines/winline-018.xml',
    texturewinline019_xml : 'res/exported/winLines/winline-019.xml',
    texturewinline020_xml : 'res/exported/winLines/winline-020.xml',
    texturewinline021_xml : 'res/exported/winLines/winline-021.xml',
    texturewinline022_xml : 'res/exported/winLines/winline-022.xml',
    texturewinline023_xml : 'res/exported/winLines/winline-023.xml',
    texturewinline024_xml : 'res/exported/winLines/winline-024.xml',
    texturewinline025_xml : 'res/exported/winLines/winline-025.xml',
    texturewinline026_xml : 'res/exported/winLines/winline-026.xml',
    texturewinline027_xml : 'res/exported/winLines/winline-027.xml',
    texturewinline028_xml : 'res/exported/winLines/winline-028.xml',
    texturewinline029_xml : 'res/exported/winLines/winline-029.xml',
    texturewinline030_xml : 'res/exported/winLines/winline-030.xml',
    texturewinline031_xml : 'res/exported/winLines/winline-031.xml',
    texturewinline032_xml : 'res/exported/winLines/winline-032.xml',
    texturewinline033_xml : 'res/exported/winLines/winline-033.xml',
    texturewinline034_xml : 'res/exported/winLines/winline-034.xml',
    texturewinline035_xml : 'res/exported/winLines/winline-035.xml',
    texturewinline036_xml : 'res/exported/winLines/winline-036.xml',
    texturewinline037_xml : 'res/exported/winLines/winline-037.xml',
    texturewinline038_xml : 'res/exported/winLines/winline-038.xml',
    texturewinline039_xml : 'res/exported/winLines/winline-039.xml',
    texturewinline040_xml : 'res/exported/winLines/winline-040.xml',
    texturewinline041_xml : 'res/exported/winLines/winline-041.xml',
    texturewinline042_xml : 'res/exported/winLines/winline-042.xml',
    texturewinline043_xml : 'res/exported/winLines/winline-043.xml',
    texturewinline044_xml : 'res/exported/winLines/winline-044.xml',
    texturewinline045_xml : 'res/exported/winLines/winline-045.xml',
    texturewinline046_xml : 'res/exported/winLines/winline-046.xml',
    texturewinline047_xml : 'res/exported/winLines/winline-047.xml',
    texturewinline048_xml : 'res/exported/winLines/winline-048.xml',
    texturewinline049_xml : 'res/exported/winLines/winline-049.xml',
    texturewinline050_xml : 'res/exported/winLines/winline-050.xml'
};

var g_maingame = [
    //image
    {src:res.textureControl_png},
    {src:res.textureTablet_png},
    {src:res.textureAssets01_png},
    {src:res.textureAssets02_png},
    {src:res.textureLine01_png},
    {src:res.textureLine02_png},
    {src:res.textureLine03_png},
    //tmx
    //{src:res.level01_tmx},

    //plist
    {src:res.textureControl_plist},
    {src:res.textureTablet_plist},
    {src:res.textureAssets01_plist},
    {src:res.textureAssets02_plist},
    {src:res.textureLine01_plist},
    {src:res.textureLine02_plist},
    {src:res.textureLine03_plist},

    //xml
    {src:res.textureTile_png},
    {src:res.textureTile_xml},
    {src:res.texturewinline001_xml},
    {src:res.texturewinline002_xml},
    {src:res.texturewinline003_xml},
    {src:res.texturewinline004_xml},
    {src:res.texturewinline005_xml},
    {src:res.texturewinline006_xml},
    {src:res.texturewinline007_xml},
    {src:res.texturewinline008_xml},
    {src:res.texturewinline009_xml},
    {src:res.texturewinline010_xml},
    {src:res.texturewinline011_xml},
    {src:res.texturewinline012_xml},
    {src:res.texturewinline013_xml},
    {src:res.texturewinline014_xml},
    {src:res.texturewinline015_xml},
    {src:res.texturewinline016_xml},
    {src:res.texturewinline017_xml},
    {src:res.texturewinline018_xml},
    {src:res.texturewinline019_xml},
    {src:res.texturewinline010_xml},
    {src:res.texturewinline011_xml},
    {src:res.texturewinline012_xml},
    {src:res.texturewinline013_xml},
    {src:res.texturewinline014_xml},
    {src:res.texturewinline015_xml},
    {src:res.texturewinline016_xml},
    {src:res.texturewinline017_xml},
    {src:res.texturewinline018_xml},
    {src:res.texturewinline019_xml},
    {src:res.texturewinline020_xml},
    {src:res.texturewinline021_xml},
    {src:res.texturewinline022_xml},
    {src:res.texturewinline023_xml},
    {src:res.texturewinline024_xml},
    {src:res.texturewinline025_xml},
    {src:res.texturewinline026_xml},
    {src:res.texturewinline027_xml},
    {src:res.texturewinline028_xml},
    {src:res.texturewinline029_xml},
    {src:res.texturewinline030_xml},
    {src:res.texturewinline031_xml},
    {src:res.texturewinline032_xml},
    {src:res.texturewinline033_xml},
    {src:res.texturewinline034_xml},
    {src:res.texturewinline035_xml},
    {src:res.texturewinline036_xml},
    {src:res.texturewinline037_xml},
    {src:res.texturewinline038_xml},
    {src:res.texturewinline039_xml},
    {src:res.texturewinline040_xml},
    {src:res.texturewinline041_xml},
    {src:res.texturewinline042_xml},
    {src:res.texturewinline043_xml},
    {src:res.texturewinline044_xml},
    {src:res.texturewinline045_xml},
    {src:res.texturewinline046_xml},
    {src:res.texturewinline047_xml},
    {src:res.texturewinline048_xml},
    {src:res.texturewinline049_xml},
    {src:res.texturewinline050_xml}
];